// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: rpc/response.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode is the transport-neutral classification of an application Error.
type ErrorCode int32

const (
	// INVALID is the proto zero value; together with OK it means "no error"
	// (nilifyIfEmpty treats both as a nil error).
	ErrorCode_INVALID ErrorCode = 0
	// OK indicates success / no error.
	ErrorCode_OK ErrorCode = 1
	// INVALID_REQUEST: the request was malformed or invalid for the current state.
	ErrorCode_INVALID_REQUEST ErrorCode = 2
	// DEADLINE_EXCEEDED: the operation did not complete in time.
	ErrorCode_DEADLINE_EXCEEDED ErrorCode = 3
	// NOT_FOUND: the requested resource does not exist.
	ErrorCode_NOT_FOUND ErrorCode = 4
	// ALREADY_EXISTS: a resource with the same client-provided identity (e.g. a
	// name) already exists.
	ErrorCode_ALREADY_EXISTS ErrorCode = 5
	// RESOURCE_EXHAUSTED: a quota or limit has been reached.
	ErrorCode_RESOURCE_EXHAUSTED ErrorCode = 6
	// UNIMPLEMENTED: the requested method is not implemented.
	ErrorCode_UNIMPLEMENTED ErrorCode = 7
	// INTERNAL: an unexpected server-side failure.
	ErrorCode_INTERNAL ErrorCode = 8
	// ID_COLLISION: a randomly generated id already exists; the caller should
	// regenerate the id and retry. This is internal and never surfaced to clients
	// (ErrorToGRPC collapses it to INTERNAL).
	ErrorCode_ID_COLLISION ErrorCode = 9
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "INVALID",
		1: "OK",
		2: "INVALID_REQUEST",
		3: "DEADLINE_EXCEEDED",
		4: "NOT_FOUND",
		5: "ALREADY_EXISTS",
		6: "RESOURCE_EXHAUSTED",
		7: "UNIMPLEMENTED",
		8: "INTERNAL",
		9: "ID_COLLISION",
	}
	ErrorCode_value = map[string]int32{
		"INVALID":            0,
		"OK":                 1,
		"INVALID_REQUEST":    2,
		"DEADLINE_EXCEEDED":  3,
		"NOT_FOUND":          4,
		"ALREADY_EXISTS":     5,
		"RESOURCE_EXHAUSTED": 6,
		"UNIMPLEMENTED":      7,
		"INTERNAL":           8,
		"ID_COLLISION":       9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_response_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_rpc_response_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_rpc_response_proto_rawDescGZIP(), []int{0}
}

// Error is a deterministic application (domain) error produced by an application
// core and carried back in Response.error. It is transport-neutral; the front
// server maps it to a gRPC status via ErrorToGRPC.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code is the transport-neutral error classification.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=com.evrblk.monstera.rpc.ErrorCode" json:"code,omitempty"`
	// message is a human-readable description of the error.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// context holds structured key/value details about the error (e.g. the
	// offending field or limit), surfaced to clients as errdetails.ErrorInfo.
	Context       []*ErrorContext `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_rpc_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_rpc_response_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_INVALID
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetContext() []*ErrorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// ErrorContext is a single key/value pair of structured context attached to an
// Error.
type ErrorContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorContext) Reset() {
	*x = ErrorContext{}
	mi := &file_rpc_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorContext) ProtoMessage() {}

func (x *ErrorContext) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorContext.ProtoReflect.Descriptor instead.
func (*ErrorContext) Descriptor() ([]byte, []int) {
	return file_rpc_response_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorContext) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ErrorContext) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Response is the envelope returned by an application core for an RPC.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is the marshaled response payload.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// error is the application error, set when the RPC failed at the domain level
	// (nil/INVALID/OK code means success).
	Error         *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_rpc_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rpc_response_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Request is the envelope sent to an application core for an RPC.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// method_number selects which core method to dispatch to.
	MethodNumber int32 `protobuf:"varint,1,opt,name=method_number,json=methodNumber,proto3" json:"method_number,omitempty"`
	// data is the marshaled request payload for the selected method.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// now is the request timestamp in Unix nanoseconds. For updates it is stamped
	// by the leader before the entry is appended to the Raft log, so every replica
	// applies the same value deterministically; the application core must read it
	// here rather than calling time.Now() at apply time.
	Now           int64 `protobuf:"varint,3,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rpc_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rpc_response_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetMethodNumber() int32 {
	if x != nil {
		return x.MethodNumber
	}
	return 0
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Request) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

var File_rpc_response_proto protoreflect.FileDescriptor

const file_rpc_response_proto_rawDesc = "" +
	"\n" +
	"\x12rpc/response.proto\x12\x17com.evrblk.monstera.rpc\"\x9a\x01\n" +
	"\x05Error\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".com.evrblk.monstera.rpc.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\acontext\x18\x03 \x03(\v2%.com.evrblk.monstera.rpc.ErrorContextR\acontext\"6\n" +
	"\fErrorContext\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"T\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1e.com.evrblk.monstera.rpc.ErrorR\x05error\"T\n" +
	"\aRequest\x12#\n" +
	"\rmethod_number\x18\x01 \x01(\x05R\fmethodNumber\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03now\x18\x03 \x01(\x03R\x03now*\xba\x01\n" +
	"\tErrorCode\x12\v\n" +
	"\aINVALID\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x02\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x03\x12\r\n" +
	"\tNOT_FOUND\x10\x04\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x05\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\x06\x12\x11\n" +
	"\rUNIMPLEMENTED\x10\a\x12\f\n" +
	"\bINTERNAL\x10\b\x12\x10\n" +
	"\fID_COLLISION\x10\tB Z\x1egithub.com/evrblk/monstera/rpcb\x06proto3"

var (
	file_rpc_response_proto_rawDescOnce sync.Once
	file_rpc_response_proto_rawDescData []byte
)

func file_rpc_response_proto_rawDescGZIP() []byte {
	file_rpc_response_proto_rawDescOnce.Do(func() {
		file_rpc_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_response_proto_rawDesc), len(file_rpc_response_proto_rawDesc)))
	})
	return file_rpc_response_proto_rawDescData
}

var file_rpc_response_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_response_proto_goTypes = []any{
	(ErrorCode)(0),       // 0: com.evrblk.monstera.rpc.ErrorCode
	(*Error)(nil),        // 1: com.evrblk.monstera.rpc.Error
	(*ErrorContext)(nil), // 2: com.evrblk.monstera.rpc.ErrorContext
	(*Response)(nil),     // 3: com.evrblk.monstera.rpc.Response
	(*Request)(nil),      // 4: com.evrblk.monstera.rpc.Request
}
var file_rpc_response_proto_depIdxs = []int32{
	0, // 0: com.evrblk.monstera.rpc.Error.code:type_name -> com.evrblk.monstera.rpc.ErrorCode
	2, // 1: com.evrblk.monstera.rpc.Error.context:type_name -> com.evrblk.monstera.rpc.ErrorContext
	1, // 2: com.evrblk.monstera.rpc.Response.error:type_name -> com.evrblk.monstera.rpc.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_response_proto_init() }
func file_rpc_response_proto_init() {
	if File_rpc_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_response_proto_rawDesc), len(file_rpc_response_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_response_proto_goTypes,
		DependencyIndexes: file_rpc_response_proto_depIdxs,
		EnumInfos:         file_rpc_response_proto_enumTypes,
		MessageInfos:      file_rpc_response_proto_msgTypes,
	}.Build()
	File_rpc_response_proto = out.File
	file_rpc_response_proto_goTypes = nil
	file_rpc_response_proto_depIdxs = nil
}
