// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: transport/grpc/monsterapb/api.proto

package monsterapb

import (
	cluster "github.com/evrblk/monstera/cluster"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftState int32

const (
	RaftState_RAFT_STATE_INVALID   RaftState = 0
	RaftState_RAFT_STATE_FOLLOWER  RaftState = 1
	RaftState_RAFT_STATE_CANDIDATE RaftState = 2
	RaftState_RAFT_STATE_LEADER    RaftState = 3
	RaftState_RAFT_STATE_SHUTDOWN  RaftState = 4
	// A dormant replica being seeded by the shard-split pipeline; no Raft yet.
	RaftState_RAFT_STATE_SEEDING RaftState = 5
)

// Enum value maps for RaftState.
var (
	RaftState_name = map[int32]string{
		0: "RAFT_STATE_INVALID",
		1: "RAFT_STATE_FOLLOWER",
		2: "RAFT_STATE_CANDIDATE",
		3: "RAFT_STATE_LEADER",
		4: "RAFT_STATE_SHUTDOWN",
		5: "RAFT_STATE_SEEDING",
	}
	RaftState_value = map[string]int32{
		"RAFT_STATE_INVALID":   0,
		"RAFT_STATE_FOLLOWER":  1,
		"RAFT_STATE_CANDIDATE": 2,
		"RAFT_STATE_LEADER":    3,
		"RAFT_STATE_SHUTDOWN":  4,
		"RAFT_STATE_SEEDING":   5,
	}
)

func (x RaftState) Enum() *RaftState {
	p := new(RaftState)
	*p = x
	return p
}

func (x RaftState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftState) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_grpc_monsterapb_api_proto_enumTypes[0].Descriptor()
}

func (RaftState) Type() protoreflect.EnumType {
	return &file_transport_grpc_monsterapb_api_proto_enumTypes[0]
}

func (x RaftState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftState.Descriptor instead.
func (RaftState) EnumDescriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{0}
}

type UpdateRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Payload []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Shard key routing the request to its owning shard. Absent for
	// direct-shard requests addressed by shard_id only.
	ShardKey        *uint32 `protobuf:"fixed32,2,opt,name=shard_key,json=shardKey,proto3,oneof" json:"shard_key,omitempty"`
	ApplicationName string  `protobuf:"bytes,3,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	ShardId         string  `protobuf:"bytes,4,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Hops            int32   `protobuf:"varint,5,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateRequest) GetShardKey() uint32 {
	if x != nil && x.ShardKey != nil {
		return *x.ShardKey
	}
	return 0
}

func (x *UpdateRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *UpdateRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *UpdateRequest) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReadRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Payload                []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	AllowReadFromFollowers bool                   `protobuf:"varint,2,opt,name=allow_read_from_followers,json=allowReadFromFollowers,proto3" json:"allow_read_from_followers,omitempty"`
	// Shard key routing the request to its owning shard. Absent for
	// direct-shard requests addressed by shard_id only.
	ShardKey        *uint32 `protobuf:"fixed32,3,opt,name=shard_key,json=shardKey,proto3,oneof" json:"shard_key,omitempty"`
	ApplicationName string  `protobuf:"bytes,4,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	ShardId         string  `protobuf:"bytes,5,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Hops            int32   `protobuf:"varint,6,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReadRequest) GetAllowReadFromFollowers() bool {
	if x != nil {
		return x.AllowReadFromFollowers
	}
	return false
}

func (x *ReadRequest) GetShardKey() uint32 {
	if x != nil && x.ShardKey != nil {
		return *x.ShardKey
	}
	return 0
}

func (x *ReadRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *ReadRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ReadRequest) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListReplicaStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicaStatesRequest) Reset() {
	*x = ListReplicaStatesRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicaStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicaStatesRequest) ProtoMessage() {}

func (x *ListReplicaStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicaStatesRequest.ProtoReflect.Descriptor instead.
func (*ListReplicaStatesRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{4}
}

type ListReplicaStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaStates []*ReplicaState        `protobuf:"bytes,1,rep,name=replica_states,json=replicaStates,proto3" json:"replica_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicaStatesResponse) Reset() {
	*x = ListReplicaStatesResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicaStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicaStatesResponse) ProtoMessage() {}

func (x *ListReplicaStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicaStatesResponse.ProtoReflect.Descriptor instead.
func (*ListReplicaStatesResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListReplicaStatesResponse) GetReplicaStates() []*ReplicaState {
	if x != nil {
		return x.ReplicaStates
	}
	return nil
}

type ListReplicaSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicaSnapshotsRequest) Reset() {
	*x = ListReplicaSnapshotsRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicaSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicaSnapshotsRequest) ProtoMessage() {}

func (x *ListReplicaSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicaSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListReplicaSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListReplicaSnapshotsRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

type ListReplicaSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*RaftSnapshot        `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplicaSnapshotsResponse) Reset() {
	*x = ListReplicaSnapshotsResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplicaSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplicaSnapshotsResponse) ProtoMessage() {}

func (x *ListReplicaSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplicaSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListReplicaSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListReplicaSnapshotsResponse) GetSnapshots() []*RaftSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type TriggerSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotRequest) Reset() {
	*x = TriggerSnapshotRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotRequest) ProtoMessage() {}

func (x *TriggerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerSnapshotRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

type TriggerSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotResponse) Reset() {
	*x = TriggerSnapshotResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotResponse) ProtoMessage() {}

func (x *TriggerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{9}
}

type LeadershipTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadershipTransferRequest) Reset() {
	*x = LeadershipTransferRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipTransferRequest) ProtoMessage() {}

func (x *LeadershipTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadershipTransferRequest.ProtoReflect.Descriptor instead.
func (*LeadershipTransferRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{10}
}

func (x *LeadershipTransferRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

type LeadershipTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadershipTransferResponse) Reset() {
	*x = LeadershipTransferResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipTransferResponse) ProtoMessage() {}

func (x *LeadershipTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadershipTransferResponse.ProtoReflect.Descriptor instead.
func (*LeadershipTransferResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{11}
}

type SplitCutoffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitCutoffRequest) Reset() {
	*x = SplitCutoffRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitCutoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitCutoffRequest) ProtoMessage() {}

func (x *SplitCutoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitCutoffRequest.ProtoReflect.Descriptor instead.
func (*SplitCutoffRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{12}
}

func (x *SplitCutoffRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type SplitCutoffResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent log index the shard froze at.
	CutoffIndex   uint64 `protobuf:"varint,1,opt,name=cutoff_index,json=cutoffIndex,proto3" json:"cutoff_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitCutoffResponse) Reset() {
	*x = SplitCutoffResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitCutoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitCutoffResponse) ProtoMessage() {}

func (x *SplitCutoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitCutoffResponse.ProtoReflect.Descriptor instead.
func (*SplitCutoffResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{13}
}

func (x *SplitCutoffResponse) GetCutoffIndex() uint64 {
	if x != nil {
		return x.CutoffIndex
	}
	return 0
}

type ReplicaState struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	RaftStats *RaftStats             `protobuf:"bytes,2,opt,name=raft_stats,json=raftStats,proto3" json:"raft_stats,omitempty"`
	// Set for dormant replicas of an ACTIVATING shard (split in progress):
	// seeding is true and seeded_index is the parent log index the replica's
	// durable seed has reached. raft_stats.state is RAFT_STATE_SEEDING and the
	// remaining stats are zero.
	Seeding     bool   `protobuf:"varint,3,opt,name=seeding,proto3" json:"seeding,omitempty"`
	SeededIndex uint64 `protobuf:"varint,4,opt,name=seeded_index,json=seededIndex,proto3" json:"seeded_index,omitempty"`
	// True once this (parent) replica applied the split CUTOFF.
	Frozen        bool `protobuf:"varint,5,opt,name=frozen,proto3" json:"frozen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaState) Reset() {
	*x = ReplicaState{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaState) ProtoMessage() {}

func (x *ReplicaState) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaState.ProtoReflect.Descriptor instead.
func (*ReplicaState) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{14}
}

func (x *ReplicaState) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReplicaState) GetRaftStats() *RaftStats {
	if x != nil {
		return x.RaftStats
	}
	return nil
}

func (x *ReplicaState) GetSeeding() bool {
	if x != nil {
		return x.Seeding
	}
	return false
}

func (x *ReplicaState) GetSeededIndex() uint64 {
	if x != nil {
		return x.SeededIndex
	}
	return 0
}

func (x *ReplicaState) GetFrozen() bool {
	if x != nil {
		return x.Frozen
	}
	return false
}

type RaftStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	State             RaftState              `protobuf:"varint,1,opt,name=state,proto3,enum=com.evrblk.monstera.monsterapb.RaftState" json:"state,omitempty"`
	Term              uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastLogIndex      uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm       uint64                 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	CommitIndex       uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex      uint64                 `protobuf:"varint,6,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	FsmPending        uint64                 `protobuf:"varint,7,opt,name=fsm_pending,json=fsmPending,proto3" json:"fsm_pending,omitempty"`
	LastSnapshotIndex uint64                 `protobuf:"varint,8,opt,name=last_snapshot_index,json=lastSnapshotIndex,proto3" json:"last_snapshot_index,omitempty"`
	LastSnapshotTerm  uint64                 `protobuf:"varint,9,opt,name=last_snapshot_term,json=lastSnapshotTerm,proto3" json:"last_snapshot_term,omitempty"`
	NumPeers          int32                  `protobuf:"varint,10,opt,name=num_peers,json=numPeers,proto3" json:"num_peers,omitempty"`
	LastContactNanos  int64                  `protobuf:"varint,11,opt,name=last_contact_nanos,json=lastContactNanos,proto3" json:"last_contact_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RaftStats) Reset() {
	*x = RaftStats{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftStats) ProtoMessage() {}

func (x *RaftStats) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftStats.ProtoReflect.Descriptor instead.
func (*RaftStats) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{15}
}

func (x *RaftStats) GetState() RaftState {
	if x != nil {
		return x.State
	}
	return RaftState_RAFT_STATE_INVALID
}

func (x *RaftStats) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftStats) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RaftStats) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RaftStats) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *RaftStats) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *RaftStats) GetFsmPending() uint64 {
	if x != nil {
		return x.FsmPending
	}
	return 0
}

func (x *RaftStats) GetLastSnapshotIndex() uint64 {
	if x != nil {
		return x.LastSnapshotIndex
	}
	return 0
}

func (x *RaftStats) GetLastSnapshotTerm() uint64 {
	if x != nil {
		return x.LastSnapshotTerm
	}
	return 0
}

func (x *RaftStats) GetNumPeers() int32 {
	if x != nil {
		return x.NumPeers
	}
	return 0
}

func (x *RaftStats) GetLastContactNanos() int64 {
	if x != nil {
		return x.LastContactNanos
	}
	return 0
}

type RaftSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftSnapshot) Reset() {
	*x = RaftSnapshot{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftSnapshot) ProtoMessage() {}

func (x *RaftSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftSnapshot.ProtoReflect.Descriptor instead.
func (*RaftSnapshot) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{16}
}

func (x *RaftSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftSnapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftSnapshot) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftSnapshot) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UpdateClusterConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *cluster.Config        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterConfigRequest) Reset() {
	*x = UpdateClusterConfigRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterConfigRequest) ProtoMessage() {}

func (x *UpdateClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateClusterConfigRequest) GetConfig() *cluster.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateClusterConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterConfigResponse) Reset() {
	*x = UpdateClusterConfigResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterConfigResponse) ProtoMessage() {}

func (x *UpdateClusterConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateClusterConfigResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{18}
}

type GetClusterConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterConfigRequest) Reset() {
	*x = GetClusterConfigRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterConfigRequest) ProtoMessage() {}

func (x *GetClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*GetClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{19}
}

type GetClusterConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *cluster.Config        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterConfigResponse) Reset() {
	*x = GetClusterConfigResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterConfigResponse) ProtoMessage() {}

func (x *GetClusterConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterConfigResponse.ProtoReflect.Descriptor instead.
func (*GetClusterConfigResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{20}
}

func (x *GetClusterConfigResponse) GetConfig() *cluster.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type BootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Config        *cluster.Config        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{21}
}

func (x *BootstrapRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BootstrapRequest) GetConfig() *cluster.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type BootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapResponse) Reset() {
	*x = BootstrapResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapResponse) ProtoMessage() {}

func (x *BootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapResponse.ProtoReflect.Descriptor instead.
func (*BootstrapResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{22}
}

type RaftMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	MessageType   int32                  `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     int64                  `protobuf:"varint,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessageRequest) Reset() {
	*x = RaftMessageRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageRequest) ProtoMessage() {}

func (x *RaftMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageRequest.ProtoReflect.Descriptor instead.
func (*RaftMessageRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{23}
}

func (x *RaftMessageRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *RaftMessageRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *RaftMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RaftMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type RaftMessageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MessageType         int32                  `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Message             []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResponseToMessageId int64                  `protobuf:"varint,3,opt,name=response_to_message_id,json=responseToMessageId,proto3" json:"response_to_message_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RaftMessageResponse) Reset() {
	*x = RaftMessageResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageResponse) ProtoMessage() {}

func (x *RaftMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageResponse.ProtoReflect.Descriptor instead.
func (*RaftMessageResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{24}
}

func (x *RaftMessageResponse) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *RaftMessageResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RaftMessageResponse) GetResponseToMessageId() int64 {
	if x != nil {
		return x.ResponseToMessageId
	}
	return 0
}

var File_transport_grpc_monsterapb_api_proto protoreflect.FileDescriptor

const file_transport_grpc_monsterapb_api_proto_rawDesc = "" +
	"\n" +
	"#transport/grpc/monsterapb/api.proto\x12\x1ecom.evrblk.monstera.monsterapb\x1a\x14cluster/config.proto\"\xb3\x01\n" +
	"\rUpdateRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12 \n" +
	"\tshard_key\x18\x02 \x01(\aH\x00R\bshardKey\x88\x01\x01\x12)\n" +
	"\x10application_name\x18\x03 \x01(\tR\x0fapplicationName\x12\x19\n" +
	"\bshard_id\x18\x04 \x01(\tR\ashardId\x12\x12\n" +
	"\x04hops\x18\x05 \x01(\x05R\x04hopsB\f\n" +
	"\n" +
	"_shard_key\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\xec\x01\n" +
	"\vReadRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x129\n" +
	"\x19allow_read_from_followers\x18\x02 \x01(\bR\x16allowReadFromFollowers\x12 \n" +
	"\tshard_key\x18\x03 \x01(\aH\x00R\bshardKey\x88\x01\x01\x12)\n" +
	"\x10application_name\x18\x04 \x01(\tR\x0fapplicationName\x12\x19\n" +
	"\bshard_id\x18\x05 \x01(\tR\ashardId\x12\x12\n" +
	"\x04hops\x18\x06 \x01(\x05R\x04hopsB\f\n" +
	"\n" +
	"_shard_key\"(\n" +
	"\fReadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x1a\n" +
	"\x18ListReplicaStatesRequest\"p\n" +
	"\x19ListReplicaStatesResponse\x12S\n" +
	"\x0ereplica_states\x18\x01 \x03(\v2,.com.evrblk.monstera.monsterapb.ReplicaStateR\rreplicaStates\"<\n" +
	"\x1bListReplicaSnapshotsRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\"j\n" +
	"\x1cListReplicaSnapshotsResponse\x12J\n" +
	"\tsnapshots\x18\x01 \x03(\v2,.com.evrblk.monstera.monsterapb.RaftSnapshotR\tsnapshots\"7\n" +
	"\x16TriggerSnapshotRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\"\x19\n" +
	"\x17TriggerSnapshotResponse\":\n" +
	"\x19LeadershipTransferRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\"\x1c\n" +
	"\x1aLeadershipTransferResponse\"/\n" +
	"\x12SplitCutoffRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"8\n" +
	"\x13SplitCutoffResponse\x12!\n" +
	"\fcutoff_index\x18\x01 \x01(\x04R\vcutoffIndex\"\xcc\x01\n" +
	"\fReplicaState\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12H\n" +
	"\n" +
	"raft_stats\x18\x02 \x01(\v2).com.evrblk.monstera.monsterapb.RaftStatsR\traftStats\x12\x18\n" +
	"\aseeding\x18\x03 \x01(\bR\aseeding\x12!\n" +
	"\fseeded_index\x18\x04 \x01(\x04R\vseededIndex\x12\x16\n" +
	"\x06frozen\x18\x05 \x01(\bR\x06frozen\"\xbc\x03\n" +
	"\tRaftStats\x12?\n" +
	"\x05state\x18\x01 \x01(\x0e2).com.evrblk.monstera.monsterapb.RaftStateR\x05state\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x06 \x01(\x04R\fappliedIndex\x12\x1f\n" +
	"\vfsm_pending\x18\a \x01(\x04R\n" +
	"fsmPending\x12.\n" +
	"\x13last_snapshot_index\x18\b \x01(\x04R\x11lastSnapshotIndex\x12,\n" +
	"\x12last_snapshot_term\x18\t \x01(\x04R\x10lastSnapshotTerm\x12\x1b\n" +
	"\tnum_peers\x18\n" +
	" \x01(\x05R\bnumPeers\x12,\n" +
	"\x12last_contact_nanos\x18\v \x01(\x03R\x10lastContactNanos\"\\\n" +
	"\fRaftSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"Y\n" +
	"\x1aUpdateClusterConfigRequest\x12;\n" +
	"\x06config\x18\x01 \x01(\v2#.com.evrblk.monstera.cluster.ConfigR\x06config\"\x1d\n" +
	"\x1bUpdateClusterConfigResponse\"\x19\n" +
	"\x17GetClusterConfigRequest\"W\n" +
	"\x18GetClusterConfigResponse\x12;\n" +
	"\x06config\x18\x01 \x01(\v2#.com.evrblk.monstera.cluster.ConfigR\x06config\"h\n" +
	"\x10BootstrapRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12;\n" +
	"\x06config\x18\x02 \x01(\v2#.com.evrblk.monstera.cluster.ConfigR\x06config\"\x13\n" +
	"\x11BootstrapResponse\"\x8f\x01\n" +
	"\x12RaftMessageRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\x05R\vmessageType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\x03R\tmessageId\"\x87\x01\n" +
	"\x13RaftMessageResponse\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\x05R\vmessageType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x123\n" +
	"\x16response_to_message_id\x18\x03 \x01(\x03R\x13responseToMessageId*\x9e\x01\n" +
	"\tRaftState\x12\x16\n" +
	"\x12RAFT_STATE_INVALID\x10\x00\x12\x17\n" +
	"\x13RAFT_STATE_FOLLOWER\x10\x01\x12\x18\n" +
	"\x14RAFT_STATE_CANDIDATE\x10\x02\x12\x15\n" +
	"\x11RAFT_STATE_LEADER\x10\x03\x12\x17\n" +
	"\x13RAFT_STATE_SHUTDOWN\x10\x04\x12\x16\n" +
	"\x12RAFT_STATE_SEEDING\x10\x052\xa0\v\n" +
	"\vMonsteraApi\x12i\n" +
	"\x06Update\x12-.com.evrblk.monstera.monsterapb.UpdateRequest\x1a..com.evrblk.monstera.monsterapb.UpdateResponse\"\x00\x12c\n" +
	"\x04Read\x12+.com.evrblk.monstera.monsterapb.ReadRequest\x1a,.com.evrblk.monstera.monsterapb.ReadResponse\"\x00\x12\x8a\x01\n" +
	"\x11ListReplicaStates\x128.com.evrblk.monstera.monsterapb.ListReplicaStatesRequest\x1a9.com.evrblk.monstera.monsterapb.ListReplicaStatesResponse\"\x00\x12\x93\x01\n" +
	"\x14ListReplicaSnapshots\x12;.com.evrblk.monstera.monsterapb.ListReplicaSnapshotsRequest\x1a<.com.evrblk.monstera.monsterapb.ListReplicaSnapshotsResponse\"\x00\x12\x8d\x01\n" +
	"\x12LeadershipTransfer\x129.com.evrblk.monstera.monsterapb.LeadershipTransferRequest\x1a:.com.evrblk.monstera.monsterapb.LeadershipTransferResponse\"\x00\x12x\n" +
	"\vSplitCutoff\x122.com.evrblk.monstera.monsterapb.SplitCutoffRequest\x1a3.com.evrblk.monstera.monsterapb.SplitCutoffResponse\"\x00\x12\x84\x01\n" +
	"\x0fTriggerSnapshot\x126.com.evrblk.monstera.monsterapb.TriggerSnapshotRequest\x1a7.com.evrblk.monstera.monsterapb.TriggerSnapshotResponse\"\x00\x12\x90\x01\n" +
	"\x13UpdateClusterConfig\x12:.com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest\x1a;.com.evrblk.monstera.monsterapb.UpdateClusterConfigResponse\"\x00\x12\x87\x01\n" +
	"\x10GetClusterConfig\x127.com.evrblk.monstera.monsterapb.GetClusterConfigRequest\x1a8.com.evrblk.monstera.monsterapb.GetClusterConfigResponse\"\x00\x12r\n" +
	"\tBootstrap\x120.com.evrblk.monstera.monsterapb.BootstrapRequest\x1a1.com.evrblk.monstera.monsterapb.BootstrapResponse\"\x00\x12|\n" +
	"\vRaftMessage\x122.com.evrblk.monstera.monsterapb.RaftMessageRequest\x1a3.com.evrblk.monstera.monsterapb.RaftMessageResponse\"\x00(\x010\x01B6Z4github.com/evrblk/monstera/transport/grpc/monsterapbb\x06proto3"

var (
	file_transport_grpc_monsterapb_api_proto_rawDescOnce sync.Once
	file_transport_grpc_monsterapb_api_proto_rawDescData []byte
)

func file_transport_grpc_monsterapb_api_proto_rawDescGZIP() []byte {
	file_transport_grpc_monsterapb_api_proto_rawDescOnce.Do(func() {
		file_transport_grpc_monsterapb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_grpc_monsterapb_api_proto_rawDesc), len(file_transport_grpc_monsterapb_api_proto_rawDesc)))
	})
	return file_transport_grpc_monsterapb_api_proto_rawDescData
}

var file_transport_grpc_monsterapb_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transport_grpc_monsterapb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_transport_grpc_monsterapb_api_proto_goTypes = []any{
	(RaftState)(0),                       // 0: com.evrblk.monstera.monsterapb.RaftState
	(*UpdateRequest)(nil),                // 1: com.evrblk.monstera.monsterapb.UpdateRequest
	(*UpdateResponse)(nil),               // 2: com.evrblk.monstera.monsterapb.UpdateResponse
	(*ReadRequest)(nil),                  // 3: com.evrblk.monstera.monsterapb.ReadRequest
	(*ReadResponse)(nil),                 // 4: com.evrblk.monstera.monsterapb.ReadResponse
	(*ListReplicaStatesRequest)(nil),     // 5: com.evrblk.monstera.monsterapb.ListReplicaStatesRequest
	(*ListReplicaStatesResponse)(nil),    // 6: com.evrblk.monstera.monsterapb.ListReplicaStatesResponse
	(*ListReplicaSnapshotsRequest)(nil),  // 7: com.evrblk.monstera.monsterapb.ListReplicaSnapshotsRequest
	(*ListReplicaSnapshotsResponse)(nil), // 8: com.evrblk.monstera.monsterapb.ListReplicaSnapshotsResponse
	(*TriggerSnapshotRequest)(nil),       // 9: com.evrblk.monstera.monsterapb.TriggerSnapshotRequest
	(*TriggerSnapshotResponse)(nil),      // 10: com.evrblk.monstera.monsterapb.TriggerSnapshotResponse
	(*LeadershipTransferRequest)(nil),    // 11: com.evrblk.monstera.monsterapb.LeadershipTransferRequest
	(*LeadershipTransferResponse)(nil),   // 12: com.evrblk.monstera.monsterapb.LeadershipTransferResponse
	(*SplitCutoffRequest)(nil),           // 13: com.evrblk.monstera.monsterapb.SplitCutoffRequest
	(*SplitCutoffResponse)(nil),          // 14: com.evrblk.monstera.monsterapb.SplitCutoffResponse
	(*ReplicaState)(nil),                 // 15: com.evrblk.monstera.monsterapb.ReplicaState
	(*RaftStats)(nil),                    // 16: com.evrblk.monstera.monsterapb.RaftStats
	(*RaftSnapshot)(nil),                 // 17: com.evrblk.monstera.monsterapb.RaftSnapshot
	(*UpdateClusterConfigRequest)(nil),   // 18: com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest
	(*UpdateClusterConfigResponse)(nil),  // 19: com.evrblk.monstera.monsterapb.UpdateClusterConfigResponse
	(*GetClusterConfigRequest)(nil),      // 20: com.evrblk.monstera.monsterapb.GetClusterConfigRequest
	(*GetClusterConfigResponse)(nil),     // 21: com.evrblk.monstera.monsterapb.GetClusterConfigResponse
	(*BootstrapRequest)(nil),             // 22: com.evrblk.monstera.monsterapb.BootstrapRequest
	(*BootstrapResponse)(nil),            // 23: com.evrblk.monstera.monsterapb.BootstrapResponse
	(*RaftMessageRequest)(nil),           // 24: com.evrblk.monstera.monsterapb.RaftMessageRequest
	(*RaftMessageResponse)(nil),          // 25: com.evrblk.monstera.monsterapb.RaftMessageResponse
	(*cluster.Config)(nil),               // 26: com.evrblk.monstera.cluster.Config
}
var file_transport_grpc_monsterapb_api_proto_depIdxs = []int32{
	15, // 0: com.evrblk.monstera.monsterapb.ListReplicaStatesResponse.replica_states:type_name -> com.evrblk.monstera.monsterapb.ReplicaState
	17, // 1: com.evrblk.monstera.monsterapb.ListReplicaSnapshotsResponse.snapshots:type_name -> com.evrblk.monstera.monsterapb.RaftSnapshot
	16, // 2: com.evrblk.monstera.monsterapb.ReplicaState.raft_stats:type_name -> com.evrblk.monstera.monsterapb.RaftStats
	0,  // 3: com.evrblk.monstera.monsterapb.RaftStats.state:type_name -> com.evrblk.monstera.monsterapb.RaftState
	26, // 4: com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest.config:type_name -> com.evrblk.monstera.cluster.Config
	26, // 5: com.evrblk.monstera.monsterapb.GetClusterConfigResponse.config:type_name -> com.evrblk.monstera.cluster.Config
	26, // 6: com.evrblk.monstera.monsterapb.BootstrapRequest.config:type_name -> com.evrblk.monstera.cluster.Config
	1,  // 7: com.evrblk.monstera.monsterapb.MonsteraApi.Update:input_type -> com.evrblk.monstera.monsterapb.UpdateRequest
	3,  // 8: com.evrblk.monstera.monsterapb.MonsteraApi.Read:input_type -> com.evrblk.monstera.monsterapb.ReadRequest
	5,  // 9: com.evrblk.monstera.monsterapb.MonsteraApi.ListReplicaStates:input_type -> com.evrblk.monstera.monsterapb.ListReplicaStatesRequest
	7,  // 10: com.evrblk.monstera.monsterapb.MonsteraApi.ListReplicaSnapshots:input_type -> com.evrblk.monstera.monsterapb.ListReplicaSnapshotsRequest
	11, // 11: com.evrblk.monstera.monsterapb.MonsteraApi.LeadershipTransfer:input_type -> com.evrblk.monstera.monsterapb.LeadershipTransferRequest
	13, // 12: com.evrblk.monstera.monsterapb.MonsteraApi.SplitCutoff:input_type -> com.evrblk.monstera.monsterapb.SplitCutoffRequest
	9,  // 13: com.evrblk.monstera.monsterapb.MonsteraApi.TriggerSnapshot:input_type -> com.evrblk.monstera.monsterapb.TriggerSnapshotRequest
	18, // 14: com.evrblk.monstera.monsterapb.MonsteraApi.UpdateClusterConfig:input_type -> com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest
	20, // 15: com.evrblk.monstera.monsterapb.MonsteraApi.GetClusterConfig:input_type -> com.evrblk.monstera.monsterapb.GetClusterConfigRequest
	22, // 16: com.evrblk.monstera.monsterapb.MonsteraApi.Bootstrap:input_type -> com.evrblk.monstera.monsterapb.BootstrapRequest
	24, // 17: com.evrblk.monstera.monsterapb.MonsteraApi.RaftMessage:input_type -> com.evrblk.monstera.monsterapb.RaftMessageRequest
	2,  // 18: com.evrblk.monstera.monsterapb.MonsteraApi.Update:output_type -> com.evrblk.monstera.monsterapb.UpdateResponse
	4,  // 19: com.evrblk.monstera.monsterapb.MonsteraApi.Read:output_type -> com.evrblk.monstera.monsterapb.ReadResponse
	6,  // 20: com.evrblk.monstera.monsterapb.MonsteraApi.ListReplicaStates:output_type -> com.evrblk.monstera.monsterapb.ListReplicaStatesResponse
	8,  // 21: com.evrblk.monstera.monsterapb.MonsteraApi.ListReplicaSnapshots:output_type -> com.evrblk.monstera.monsterapb.ListReplicaSnapshotsResponse
	12, // 22: com.evrblk.monstera.monsterapb.MonsteraApi.LeadershipTransfer:output_type -> com.evrblk.monstera.monsterapb.LeadershipTransferResponse
	14, // 23: com.evrblk.monstera.monsterapb.MonsteraApi.SplitCutoff:output_type -> com.evrblk.monstera.monsterapb.SplitCutoffResponse
	10, // 24: com.evrblk.monstera.monsterapb.MonsteraApi.TriggerSnapshot:output_type -> com.evrblk.monstera.monsterapb.TriggerSnapshotResponse
	19, // 25: com.evrblk.monstera.monsterapb.MonsteraApi.UpdateClusterConfig:output_type -> com.evrblk.monstera.monsterapb.UpdateClusterConfigResponse
	21, // 26: com.evrblk.monstera.monsterapb.MonsteraApi.GetClusterConfig:output_type -> com.evrblk.monstera.monsterapb.GetClusterConfigResponse
	23, // 27: com.evrblk.monstera.monsterapb.MonsteraApi.Bootstrap:output_type -> com.evrblk.monstera.monsterapb.BootstrapResponse
	25, // 28: com.evrblk.monstera.monsterapb.MonsteraApi.RaftMessage:output_type -> com.evrblk.monstera.monsterapb.RaftMessageResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_transport_grpc_monsterapb_api_proto_init() }
func file_transport_grpc_monsterapb_api_proto_init() {
	if File_transport_grpc_monsterapb_api_proto != nil {
		return
	}
	file_transport_grpc_monsterapb_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_transport_grpc_monsterapb_api_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_grpc_monsterapb_api_proto_rawDesc), len(file_transport_grpc_monsterapb_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_monsterapb_api_proto_goTypes,
		DependencyIndexes: file_transport_grpc_monsterapb_api_proto_depIdxs,
		EnumInfos:         file_transport_grpc_monsterapb_api_proto_enumTypes,
		MessageInfos:      file_transport_grpc_monsterapb_api_proto_msgTypes,
	}.Build()
	File_transport_grpc_monsterapb_api_proto = out.File
	file_transport_grpc_monsterapb_api_proto_goTypes = nil
	file_transport_grpc_monsterapb_api_proto_depIdxs = nil
}
