// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: transport/grpc/monsterapb/api.proto

package monsterapb

import (
	cluster "github.com/evrblk/monstera/cluster"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftState int32

const (
	RaftState_RAFT_STATE_INVALID   RaftState = 0
	RaftState_RAFT_STATE_FOLLOWER  RaftState = 1
	RaftState_RAFT_STATE_LEADER    RaftState = 2
	RaftState_RAFT_STATE_CANDIDATE RaftState = 3
	RaftState_RAFT_STATE_SHUTDOWN  RaftState = 4
)

// Enum value maps for RaftState.
var (
	RaftState_name = map[int32]string{
		0: "RAFT_STATE_INVALID",
		1: "RAFT_STATE_FOLLOWER",
		2: "RAFT_STATE_LEADER",
		3: "RAFT_STATE_CANDIDATE",
		4: "RAFT_STATE_SHUTDOWN",
	}
	RaftState_value = map[string]int32{
		"RAFT_STATE_INVALID":   0,
		"RAFT_STATE_FOLLOWER":  1,
		"RAFT_STATE_LEADER":    2,
		"RAFT_STATE_CANDIDATE": 3,
		"RAFT_STATE_SHUTDOWN":  4,
	}
)

func (x RaftState) Enum() *RaftState {
	p := new(RaftState)
	*p = x
	return p
}

func (x RaftState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftState) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_grpc_monsterapb_api_proto_enumTypes[0].Descriptor()
}

func (RaftState) Type() protoreflect.EnumType {
	return &file_transport_grpc_monsterapb_api_proto_enumTypes[0]
}

func (x RaftState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftState.Descriptor instead.
func (RaftState) EnumDescriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{0}
}

type UpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Payload         []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ShardKey        []byte                 `protobuf:"bytes,2,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	ApplicationName string                 `protobuf:"bytes,3,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	ShardId         string                 `protobuf:"bytes,4,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId       string                 `protobuf:"bytes,5,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Hops            int32                  `protobuf:"varint,6,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateRequest) GetShardKey() []byte {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

func (x *UpdateRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *UpdateRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *UpdateRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *UpdateRequest) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReadRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Payload                []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	AllowReadFromFollowers bool                   `protobuf:"varint,2,opt,name=allow_read_from_followers,json=allowReadFromFollowers,proto3" json:"allow_read_from_followers,omitempty"`
	ShardKey               []byte                 `protobuf:"bytes,3,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	ApplicationName        string                 `protobuf:"bytes,4,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	ShardId                string                 `protobuf:"bytes,5,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId              string                 `protobuf:"bytes,6,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Hops                   int32                  `protobuf:"varint,7,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReadRequest) GetAllowReadFromFollowers() bool {
	if x != nil {
		return x.AllowReadFromFollowers
	}
	return false
}

func (x *ReadRequest) GetShardKey() []byte {
	if x != nil {
		return x.ShardKey
	}
	return nil
}

func (x *ReadRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *ReadRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ReadRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReadRequest) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      []*ReplicaState        `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetReplicas() []*ReplicaState {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type TriggerSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotRequest) Reset() {
	*x = TriggerSnapshotRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotRequest) ProtoMessage() {}

func (x *TriggerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerSnapshotRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

type TriggerSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotResponse) Reset() {
	*x = TriggerSnapshotResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotResponse) ProtoMessage() {}

func (x *TriggerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{7}
}

type LeadershipTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadershipTransferRequest) Reset() {
	*x = LeadershipTransferRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipTransferRequest) ProtoMessage() {}

func (x *LeadershipTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadershipTransferRequest.ProtoReflect.Descriptor instead.
func (*LeadershipTransferRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{8}
}

func (x *LeadershipTransferRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

type LeadershipTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadershipTransferResponse) Reset() {
	*x = LeadershipTransferResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadershipTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadershipTransferResponse) ProtoMessage() {}

func (x *LeadershipTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadershipTransferResponse.ProtoReflect.Descriptor instead.
func (*LeadershipTransferResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{9}
}

type ReplicaState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	RaftState     RaftState              `protobuf:"varint,2,opt,name=raft_state,json=raftState,proto3,enum=com.evrblk.monstera.monsterapb.RaftState" json:"raft_state,omitempty"`
	RaftStats     map[string]string      `protobuf:"bytes,3,rep,name=raft_stats,json=raftStats,proto3" json:"raft_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Snapshots     []*RaftSnapshot        `protobuf:"bytes,4,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaState) Reset() {
	*x = ReplicaState{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaState) ProtoMessage() {}

func (x *ReplicaState) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaState.ProtoReflect.Descriptor instead.
func (*ReplicaState) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{10}
}

func (x *ReplicaState) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReplicaState) GetRaftState() RaftState {
	if x != nil {
		return x.RaftState
	}
	return RaftState_RAFT_STATE_INVALID
}

func (x *ReplicaState) GetRaftStats() map[string]string {
	if x != nil {
		return x.RaftStats
	}
	return nil
}

func (x *ReplicaState) GetSnapshots() []*RaftSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type RaftSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftSnapshot) Reset() {
	*x = RaftSnapshot{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftSnapshot) ProtoMessage() {}

func (x *RaftSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftSnapshot.ProtoReflect.Descriptor instead.
func (*RaftSnapshot) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{11}
}

func (x *RaftSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftSnapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftSnapshot) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftSnapshot) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UpdateClusterConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *cluster.Config        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterConfigRequest) Reset() {
	*x = UpdateClusterConfigRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterConfigRequest) ProtoMessage() {}

func (x *UpdateClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateClusterConfigRequest) GetConfig() *cluster.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateClusterConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClusterConfigResponse) Reset() {
	*x = UpdateClusterConfigResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClusterConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClusterConfigResponse) ProtoMessage() {}

func (x *UpdateClusterConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClusterConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateClusterConfigResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{13}
}

type RaftMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId     string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	MessageType   int32                  `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     int64                  `protobuf:"varint,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessageRequest) Reset() {
	*x = RaftMessageRequest{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageRequest) ProtoMessage() {}

func (x *RaftMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageRequest.ProtoReflect.Descriptor instead.
func (*RaftMessageRequest) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{14}
}

func (x *RaftMessageRequest) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *RaftMessageRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *RaftMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RaftMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type RaftMessageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MessageType         int32                  `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Message             []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResponseToMessageId int64                  `protobuf:"varint,3,opt,name=response_to_message_id,json=responseToMessageId,proto3" json:"response_to_message_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RaftMessageResponse) Reset() {
	*x = RaftMessageResponse{}
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessageResponse) ProtoMessage() {}

func (x *RaftMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_monsterapb_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessageResponse.ProtoReflect.Descriptor instead.
func (*RaftMessageResponse) Descriptor() ([]byte, []int) {
	return file_transport_grpc_monsterapb_api_proto_rawDescGZIP(), []int{15}
}

func (x *RaftMessageResponse) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *RaftMessageResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RaftMessageResponse) GetResponseToMessageId() int64 {
	if x != nil {
		return x.ResponseToMessageId
	}
	return 0
}

var File_transport_grpc_monsterapb_api_proto protoreflect.FileDescriptor

const file_transport_grpc_monsterapb_api_proto_rawDesc = "" +
	"\n" +
	"#transport/grpc/monsterapb/api.proto\x12\x1ecom.evrblk.monstera.monsterapb\x1a\x14cluster/config.proto\"\xbf\x01\n" +
	"\rUpdateRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1b\n" +
	"\tshard_key\x18\x02 \x01(\fR\bshardKey\x12)\n" +
	"\x10application_name\x18\x03 \x01(\tR\x0fapplicationName\x12\x19\n" +
	"\bshard_id\x18\x04 \x01(\tR\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x05 \x01(\tR\treplicaId\x12\x12\n" +
	"\x04hops\x18\x06 \x01(\x05R\x04hops\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\xf8\x01\n" +
	"\vReadRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x129\n" +
	"\x19allow_read_from_followers\x18\x02 \x01(\bR\x16allowReadFromFollowers\x12\x1b\n" +
	"\tshard_key\x18\x03 \x01(\fR\bshardKey\x12)\n" +
	"\x10application_name\x18\x04 \x01(\tR\x0fapplicationName\x12\x19\n" +
	"\bshard_id\x18\x05 \x01(\tR\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x06 \x01(\tR\treplicaId\x12\x12\n" +
	"\x04hops\x18\a \x01(\x05R\x04hops\"(\n" +
	"\fReadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x14\n" +
	"\x12HealthCheckRequest\"_\n" +
	"\x13HealthCheckResponse\x12H\n" +
	"\breplicas\x18\x01 \x03(\v2,.com.evrblk.monstera.monsterapb.ReplicaStateR\breplicas\"7\n" +
	"\x16TriggerSnapshotRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\"\x19\n" +
	"\x17TriggerSnapshotResponse\":\n" +
	"\x19LeadershipTransferRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\"\x1c\n" +
	"\x1aLeadershipTransferResponse\"\xdd\x02\n" +
	"\fReplicaState\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12H\n" +
	"\n" +
	"raft_state\x18\x02 \x01(\x0e2).com.evrblk.monstera.monsterapb.RaftStateR\traftState\x12Z\n" +
	"\n" +
	"raft_stats\x18\x03 \x03(\v2;.com.evrblk.monstera.monsterapb.ReplicaState.RaftStatsEntryR\traftStats\x12J\n" +
	"\tsnapshots\x18\x04 \x03(\v2,.com.evrblk.monstera.monsterapb.RaftSnapshotR\tsnapshots\x1a<\n" +
	"\x0eRaftStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\fRaftSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"Y\n" +
	"\x1aUpdateClusterConfigRequest\x12;\n" +
	"\x06config\x18\x01 \x01(\v2#.com.evrblk.monstera.cluster.ConfigR\x06config\"\x1d\n" +
	"\x1bUpdateClusterConfigResponse\"\x8f\x01\n" +
	"\x12RaftMessageRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\x05R\vmessageType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\x03R\tmessageId\"\x87\x01\n" +
	"\x13RaftMessageResponse\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\x05R\vmessageType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x123\n" +
	"\x16response_to_message_id\x18\x03 \x01(\x03R\x13responseToMessageId*\x86\x01\n" +
	"\tRaftState\x12\x16\n" +
	"\x12RAFT_STATE_INVALID\x10\x00\x12\x17\n" +
	"\x13RAFT_STATE_FOLLOWER\x10\x01\x12\x15\n" +
	"\x11RAFT_STATE_LEADER\x10\x02\x12\x18\n" +
	"\x14RAFT_STATE_CANDIDATE\x10\x03\x12\x17\n" +
	"\x13RAFT_STATE_SHUTDOWN\x10\x042\xff\x06\n" +
	"\vMonsteraApi\x12i\n" +
	"\x06Update\x12-.com.evrblk.monstera.monsterapb.UpdateRequest\x1a..com.evrblk.monstera.monsterapb.UpdateResponse\"\x00\x12c\n" +
	"\x04Read\x12+.com.evrblk.monstera.monsterapb.ReadRequest\x1a,.com.evrblk.monstera.monsterapb.ReadResponse\"\x00\x12x\n" +
	"\vHealthCheck\x122.com.evrblk.monstera.monsterapb.HealthCheckRequest\x1a3.com.evrblk.monstera.monsterapb.HealthCheckResponse\"\x00\x12\x8d\x01\n" +
	"\x12LeadershipTransfer\x129.com.evrblk.monstera.monsterapb.LeadershipTransferRequest\x1a:.com.evrblk.monstera.monsterapb.LeadershipTransferResponse\"\x00\x12\x84\x01\n" +
	"\x0fTriggerSnapshot\x126.com.evrblk.monstera.monsterapb.TriggerSnapshotRequest\x1a7.com.evrblk.monstera.monsterapb.TriggerSnapshotResponse\"\x00\x12\x90\x01\n" +
	"\x13UpdateClusterConfig\x12:.com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest\x1a;.com.evrblk.monstera.monsterapb.UpdateClusterConfigResponse\"\x00\x12|\n" +
	"\vRaftMessage\x122.com.evrblk.monstera.monsterapb.RaftMessageRequest\x1a3.com.evrblk.monstera.monsterapb.RaftMessageResponse\"\x00(\x010\x01B0Z.github.com/evrblk/monstera/internal/monsterapbb\x06proto3"

var (
	file_transport_grpc_monsterapb_api_proto_rawDescOnce sync.Once
	file_transport_grpc_monsterapb_api_proto_rawDescData []byte
)

func file_transport_grpc_monsterapb_api_proto_rawDescGZIP() []byte {
	file_transport_grpc_monsterapb_api_proto_rawDescOnce.Do(func() {
		file_transport_grpc_monsterapb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_grpc_monsterapb_api_proto_rawDesc), len(file_transport_grpc_monsterapb_api_proto_rawDesc)))
	})
	return file_transport_grpc_monsterapb_api_proto_rawDescData
}

var file_transport_grpc_monsterapb_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transport_grpc_monsterapb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_transport_grpc_monsterapb_api_proto_goTypes = []any{
	(RaftState)(0),                      // 0: com.evrblk.monstera.monsterapb.RaftState
	(*UpdateRequest)(nil),               // 1: com.evrblk.monstera.monsterapb.UpdateRequest
	(*UpdateResponse)(nil),              // 2: com.evrblk.monstera.monsterapb.UpdateResponse
	(*ReadRequest)(nil),                 // 3: com.evrblk.monstera.monsterapb.ReadRequest
	(*ReadResponse)(nil),                // 4: com.evrblk.monstera.monsterapb.ReadResponse
	(*HealthCheckRequest)(nil),          // 5: com.evrblk.monstera.monsterapb.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 6: com.evrblk.monstera.monsterapb.HealthCheckResponse
	(*TriggerSnapshotRequest)(nil),      // 7: com.evrblk.monstera.monsterapb.TriggerSnapshotRequest
	(*TriggerSnapshotResponse)(nil),     // 8: com.evrblk.monstera.monsterapb.TriggerSnapshotResponse
	(*LeadershipTransferRequest)(nil),   // 9: com.evrblk.monstera.monsterapb.LeadershipTransferRequest
	(*LeadershipTransferResponse)(nil),  // 10: com.evrblk.monstera.monsterapb.LeadershipTransferResponse
	(*ReplicaState)(nil),                // 11: com.evrblk.monstera.monsterapb.ReplicaState
	(*RaftSnapshot)(nil),                // 12: com.evrblk.monstera.monsterapb.RaftSnapshot
	(*UpdateClusterConfigRequest)(nil),  // 13: com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest
	(*UpdateClusterConfigResponse)(nil), // 14: com.evrblk.monstera.monsterapb.UpdateClusterConfigResponse
	(*RaftMessageRequest)(nil),          // 15: com.evrblk.monstera.monsterapb.RaftMessageRequest
	(*RaftMessageResponse)(nil),         // 16: com.evrblk.monstera.monsterapb.RaftMessageResponse
	nil,                                 // 17: com.evrblk.monstera.monsterapb.ReplicaState.RaftStatsEntry
	(*cluster.Config)(nil),              // 18: com.evrblk.monstera.cluster.Config
}
var file_transport_grpc_monsterapb_api_proto_depIdxs = []int32{
	11, // 0: com.evrblk.monstera.monsterapb.HealthCheckResponse.replicas:type_name -> com.evrblk.monstera.monsterapb.ReplicaState
	0,  // 1: com.evrblk.monstera.monsterapb.ReplicaState.raft_state:type_name -> com.evrblk.monstera.monsterapb.RaftState
	17, // 2: com.evrblk.monstera.monsterapb.ReplicaState.raft_stats:type_name -> com.evrblk.monstera.monsterapb.ReplicaState.RaftStatsEntry
	12, // 3: com.evrblk.monstera.monsterapb.ReplicaState.snapshots:type_name -> com.evrblk.monstera.monsterapb.RaftSnapshot
	18, // 4: com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest.config:type_name -> com.evrblk.monstera.cluster.Config
	1,  // 5: com.evrblk.monstera.monsterapb.MonsteraApi.Update:input_type -> com.evrblk.monstera.monsterapb.UpdateRequest
	3,  // 6: com.evrblk.monstera.monsterapb.MonsteraApi.Read:input_type -> com.evrblk.monstera.monsterapb.ReadRequest
	5,  // 7: com.evrblk.monstera.monsterapb.MonsteraApi.HealthCheck:input_type -> com.evrblk.monstera.monsterapb.HealthCheckRequest
	9,  // 8: com.evrblk.monstera.monsterapb.MonsteraApi.LeadershipTransfer:input_type -> com.evrblk.monstera.monsterapb.LeadershipTransferRequest
	7,  // 9: com.evrblk.monstera.monsterapb.MonsteraApi.TriggerSnapshot:input_type -> com.evrblk.monstera.monsterapb.TriggerSnapshotRequest
	13, // 10: com.evrblk.monstera.monsterapb.MonsteraApi.UpdateClusterConfig:input_type -> com.evrblk.monstera.monsterapb.UpdateClusterConfigRequest
	15, // 11: com.evrblk.monstera.monsterapb.MonsteraApi.RaftMessage:input_type -> com.evrblk.monstera.monsterapb.RaftMessageRequest
	2,  // 12: com.evrblk.monstera.monsterapb.MonsteraApi.Update:output_type -> com.evrblk.monstera.monsterapb.UpdateResponse
	4,  // 13: com.evrblk.monstera.monsterapb.MonsteraApi.Read:output_type -> com.evrblk.monstera.monsterapb.ReadResponse
	6,  // 14: com.evrblk.monstera.monsterapb.MonsteraApi.HealthCheck:output_type -> com.evrblk.monstera.monsterapb.HealthCheckResponse
	10, // 15: com.evrblk.monstera.monsterapb.MonsteraApi.LeadershipTransfer:output_type -> com.evrblk.monstera.monsterapb.LeadershipTransferResponse
	8,  // 16: com.evrblk.monstera.monsterapb.MonsteraApi.TriggerSnapshot:output_type -> com.evrblk.monstera.monsterapb.TriggerSnapshotResponse
	14, // 17: com.evrblk.monstera.monsterapb.MonsteraApi.UpdateClusterConfig:output_type -> com.evrblk.monstera.monsterapb.UpdateClusterConfigResponse
	16, // 18: com.evrblk.monstera.monsterapb.MonsteraApi.RaftMessage:output_type -> com.evrblk.monstera.monsterapb.RaftMessageResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_transport_grpc_monsterapb_api_proto_init() }
func file_transport_grpc_monsterapb_api_proto_init() {
	if File_transport_grpc_monsterapb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_grpc_monsterapb_api_proto_rawDesc), len(file_transport_grpc_monsterapb_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_monsterapb_api_proto_goTypes,
		DependencyIndexes: file_transport_grpc_monsterapb_api_proto_depIdxs,
		EnumInfos:         file_transport_grpc_monsterapb_api_proto_enumTypes,
		MessageInfos:      file_transport_grpc_monsterapb_api_proto_msgTypes,
	}.Build()
	File_transport_grpc_monsterapb_api_proto = out.File
	file_transport_grpc_monsterapb_api_proto_goTypes = nil
	file_transport_grpc_monsterapb_api_proto_depIdxs = nil
}
