package codegen

import (
	"fmt"
	"strings"
)

const (
	monsteraPkg          = "github.com/evrblk/monstera"
	mrpcPkg              = "github.com/evrblk/monstera/rpc"
	clusterPkg           = "github.com/evrblk/monstera/cluster"
	generatedCodeComment = "Code generated by `monstera code generate`. DO NOT EDIT."
)

func firstCharToLower(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// resolveStubCores maps a stub's core names to their definitions. Manifests
// loaded through LoadMonsteraYaml are already validated, so a miss can only
// happen for a hand-built config that bypassed Validate.
func resolveStubCores(cfg *MonsteraYaml, stub *MonsteraStub) ([]*MonsteraCore, error) {
	cores := make([]*MonsteraCore, len(stub.Cores))
	for i, coreName := range stub.Cores {
		found := false
		for _, core := range cfg.Cores {
			if core.Name == coreName {
				cores[i] = core
				found = true
				break
			}
		}
		if !found {
			return nil, fmt.Errorf("stub %q references unknown core %q", stub.Name, coreName)
		}
	}
	return cores, nil
}
