package codegen

import "strings"

const (
	monsteraPkg          = "github.com/evrblk/monstera"
	mrpcPkg              = "github.com/evrblk/monstera/rpc"
	generatedCodeComment = "Code generated by `monstera code generate`. DO NOT EDIT."
)

func firstCharToLower(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
