// Code generated by `monstera code generate`. DO NOT EDIT.

package codegen

import (
	"fmt"
	monstera "github.com/evrblk/monstera"
	types "github.com/evrblk/monstera/internal/integration_test/codegen/types"
	mrpc "github.com/evrblk/monstera/rpc"
	prometheus "github.com/prometheus/client_golang/prometheus"
	"io"
	"time"
)

var (
	monsteraCoreMethodDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Help:                            "Monstera core method duration",
		Name:                            "monstera_core_method_duration_seconds",
		NativeHistogramBucketFactor:     1.1,
		NativeHistogramMaxBucketNumber:  100,
		NativeHistogramMinResetDuration: time.Hour,
	}, []string{"core", "method", "shard", "replica"})
	monsteraCoreMethodCount = prometheus.NewCounterVec(prometheus.CounterOpts{
		Help: "Monstera core method count",
		Name: "monstera_core_method_count",
	}, []string{"core", "method", "shard", "replica"})
)

type MyCoreCoreAdapter struct {
	shardId   string
	replicaId string

	myCoreCore MyCoreCoreApi
}

var _ monstera.ApplicationCore = &MyCoreCoreAdapter{}

func NewMyCoreCoreAdapter(shardId string, replicaId string, myCoreCore MyCoreCoreApi) *MyCoreCoreAdapter {
	return &MyCoreCoreAdapter{
		myCoreCore: myCoreCore,
		replicaId:  replicaId,
		shardId:    shardId,
	}
}

func (a *MyCoreCoreAdapter) Snapshot() monstera.ApplicationCoreSnapshot {
	defer measureSince(monsteraCoreMethodDuration.WithLabelValues("MyCore", "Snapshot", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("MyCore", "Snapshot", a.shardId, a.replicaId).Inc()

	return a.myCoreCore.Snapshot()
}

func (a *MyCoreCoreAdapter) Restore(r io.ReadCloser) error {
	defer measureSince(monsteraCoreMethodDuration.WithLabelValues("MyCore", "Restore", a.shardId, a.replicaId), time.Now())
	monsteraCoreMethodCount.WithLabelValues("MyCore", "Restore", a.shardId, a.replicaId).Inc()

	return a.myCoreCore.Restore(r)
}

func (a *MyCoreCoreAdapter) Close() {
	a.myCoreCore.Close()
}

func (a *MyCoreCoreAdapter) Update(rpcReqBytes []byte) (*monstera.UpdateResponse, error) {
	resp := &monstera.UpdateResponse{}
	rpcResp := &mrpc.Response{}
	rpcReq := &mrpc.Request{}

	err := rpcReq.UnmarshalVT(rpcReqBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch rpcReq.MethodNumber {
	case 1:
		methodReq := types.Update1Request{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.myCoreCore.Update1(&Update1Request{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		measureSince(monsteraCoreMethodDuration.WithLabelValues("MyCore", "Update1", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("MyCore", "Update1", a.shardId, a.replicaId).Inc()
		rpcResp.Error = methodResp.ApplicationError
		methodRespBytes, err := methodResp.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		rpcResp.Data = methodRespBytes
	case 2:
		methodReq := types.Update2Request{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.myCoreCore.Update2(&Update2Request{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		measureSince(monsteraCoreMethodDuration.WithLabelValues("MyCore", "Update2", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("MyCore", "Update2", a.shardId, a.replicaId).Inc()
		rpcResp.Error = methodResp.ApplicationError
		methodRespBytes, err := methodResp.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		rpcResp.Data = methodRespBytes
	default:
		return nil, fmt.Errorf("no matching handlers")
	}

	rpcRespBytes, err := rpcResp.MarshalVT()
	if err != nil {
		return nil, err
	}
	resp.Data = rpcRespBytes

	return resp, nil
}

func (a *MyCoreCoreAdapter) Read(rpcReqBytes []byte) (*monstera.ReadResponse, error) {
	resp := &monstera.ReadResponse{}
	rpcResp := &mrpc.Response{}
	rpcReq := &mrpc.Request{}

	err := rpcReq.UnmarshalVT(rpcReqBytes)
	if err != nil {
		return nil, err
	}

	t1 := time.Now()

	switch rpcReq.MethodNumber {
	case 1:
		methodReq := types.Read1Request{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.myCoreCore.Read1(&Read1Request{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		measureSince(monsteraCoreMethodDuration.WithLabelValues("MyCore", "Read1", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("MyCore", "Read1", a.shardId, a.replicaId).Inc()
		rpcResp.Error = methodResp.ApplicationError
		methodRespBytes, err := methodResp.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		rpcResp.Data = methodRespBytes
	case 2:
		methodReq := types.Read2Request{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.myCoreCore.Read2(&Read2Request{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		measureSince(monsteraCoreMethodDuration.WithLabelValues("MyCore", "Read2", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("MyCore", "Read2", a.shardId, a.replicaId).Inc()
		rpcResp.Error = methodResp.ApplicationError
		methodRespBytes, err := methodResp.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		rpcResp.Data = methodRespBytes
	case 3:
		methodReq := types.Read3Request{}
		err := methodReq.UnmarshalBinary(rpcReq.Data)
		if err != nil {
			return nil, err
		}
		methodResp, err := a.myCoreCore.Read3(&Read3Request{
			Now:     rpcReq.Now,
			Payload: &methodReq,
		})
		if err != nil {
			return nil, err
		}
		measureSince(monsteraCoreMethodDuration.WithLabelValues("MyCore", "Read3", a.shardId, a.replicaId), t1)
		monsteraCoreMethodCount.WithLabelValues("MyCore", "Read3", a.shardId, a.replicaId).Inc()
		rpcResp.Error = methodResp.ApplicationError
		methodRespBytes, err := methodResp.Payload.MarshalBinary()
		if err != nil {
			return nil, err
		}
		rpcResp.Data = methodRespBytes
	default:
		return nil, fmt.Errorf("no matching handlers")
	}

	rpcRespBytes, err := rpcResp.MarshalVT()
	if err != nil {
		return nil, err
	}
	resp.Data = rpcRespBytes

	return resp, nil
}

func measureSince(o prometheus.Observer, t1 time.Time) {
	o.Observe(time.Since(t1).Seconds())
}
