// Code generated by `monstera code generate`. DO NOT EDIT.

package codegen

import (
	"context"
	monstera "github.com/evrblk/monstera"
	types "github.com/evrblk/monstera/internal/integration_test/codegen/types"
	mrpc "github.com/evrblk/monstera/rpc"
	"io"
)

type Read1Request = mrpc.ReadRequest[*types.Read1Request]
type Read1Response = mrpc.ReadResponse[*types.Read1Response]
type Read2Request = mrpc.ReadUnshardedRequest[*types.Read2Request]
type Read2Response = mrpc.ReadResponse[*types.Read2Response]
type Read3Request = mrpc.ReadRequest[*types.Read3Request]
type Read3Response = mrpc.ReadResponse[*types.Read3Response]
type Update1Request = mrpc.UpdateRequest[*types.Update1Request]
type Update1Response = mrpc.UpdateResponse[*types.Update1Response]
type Update2Request = mrpc.UpdateUnshardedRequest[*types.Update2Request]
type Update2Response = mrpc.UpdateResponse[*types.Update2Response]

type MyStubClientApi interface {
	Read1(ctx context.Context, req *types.Read1Request) (*types.Read1Response, error)
	Read2(ctx context.Context, req *types.Read2Request, shardId string) (*types.Read2Response, error)
	Read3(ctx context.Context, req *types.Read3Request) (*types.Read3Response, error)
	Update1(ctx context.Context, req *types.Update1Request) (*types.Update1Response, error)
	Update2(ctx context.Context, req *types.Update2Request, shardId string) (*types.Update2Response, error)

	ListShards(applicationName string) ([]string, error)
}
type MyCoreCoreApi interface {
	Snapshot() monstera.ApplicationCoreSnapshot
	Restore(reader io.ReadCloser) error
	Close()
	Read1(req *Read1Request) (*Read1Response, error)
	Read2(req *Read2Request) (*Read2Response, error)
	Read3(req *Read3Request) (*Read3Response, error)
	Update1(req *Update1Request) (*Update1Response, error)
	Update2(req *Update2Request) (*Update2Response, error)
}
