// Code generated by `monstera code generate`. DO NOT EDIT.

package codegen

import (
	"context"
	"fmt"
	monstera "github.com/evrblk/monstera"
	cluster "github.com/evrblk/monstera/cluster"
	types "github.com/evrblk/monstera/internal/integration_test/codegen/types"
	mrpc "github.com/evrblk/monstera/rpc"
	"log/slog"
	"sync"
	"time"
)

func nilifyIfEmpty(err *mrpc.Error) error {
	if err == nil || err.Code == mrpc.ErrorCode_INVALID || err.Code == mrpc.ErrorCode_OK {
		return nil
	} else {
		return err
	}
}

type MyStubMonsteraStub struct {
	monsteraClient *monstera.Client
}

var _ MyStubClientApi = &MyStubMonsteraStub{}

func (s *MyStubMonsteraStub) Read1(ctx context.Context, methodReq *types.Read1Request, opts ...mrpc.CallOption) (*types.Read1Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     1,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MyCore", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Read1Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Read2(ctx context.Context, methodReq *types.Read2Request, shardId string, opts ...mrpc.CallOption) (*types.Read2Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     2,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.ReadShard(ctx, "MyCore", shardId, false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Read2Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Read3(ctx context.Context, methodReq *types.Read3Request, opts ...mrpc.CallOption) (*types.Read3Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     3,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Read(ctx, "MyCore", methodReq.ShardKey(), true, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Read3Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Update1(ctx context.Context, methodReq *types.Update1Request, opts ...mrpc.CallOption) (*types.Update1Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     1,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.Update(ctx, "MyCore", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Update1Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Update2(ctx context.Context, methodReq *types.Update2Request, shardId string, opts ...mrpc.CallOption) (*types.Update2Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	if err := methodReq.Validate(); err != nil {
		return nil, mrpc.NewError(mrpc.InvalidRequest, err.Error())
	}

	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:             methodReqBytes,
		IdempotencyToken: settings.IdempotencyToken,
		MethodNumber:     2,
		Now:              now,
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	clientResp, err := s.monsteraClient.UpdateShard(ctx, "MyCore", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(clientResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Update2Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	if settings.ResponseMeta != nil {
		*settings.ResponseMeta = mrpc.ResponseMeta{
			Now:          now,
			RaftLogIndex: clientResp.RaftLogIndex,
		}
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) ListShards(applicationName string) ([]string, error) {
	shards, err := s.monsteraClient.ListShards(applicationName)
	if err != nil {
		return nil, err
	}
	shardIds := make([]string, len(shards))
	for i := range shards {
		shardIds[i] = shards[i].Id
	}
	return shardIds, nil
}

func NewMyStubMonsteraStub(monsteraClient *monstera.Client) *MyStubMonsteraStub {
	return &MyStubMonsteraStub{monsteraClient: monsteraClient}
}

type myCoreCoreNonclusteredAdapter struct {
	core       MyCoreCoreApi
	mu         sync.RWMutex
	id         string
	lowerBound cluster.ShardKey
	upperBound cluster.ShardKey
}

type MyStubNonclusteredApplicationCoresFactory struct {
	MyCoreCoreFactoryFunc func(shardId string, lowerBound cluster.ShardKey, upperBound cluster.ShardKey) MyCoreCoreApi
}
type MyStubNonclusteredStub struct {
	myCoreCores []*myCoreCoreNonclusteredAdapter
	logger      *slog.Logger
}

var _ MyStubClientApi = &MyStubNonclusteredStub{}

func (s *MyStubNonclusteredStub) Read1(ctx context.Context, req *types.Read1Request, opts ...mrpc.CallOption) (*types.Read1Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	for _, adapter := range s.myCoreCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.Read1(&mrpc.ReadRequest[*types.Read1Request]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MyStubNonclusteredStub) Read2(ctx context.Context, req *types.Read2Request, shardId string, opts ...mrpc.CallOption) (*types.Read2Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	for _, adapter := range s.myCoreCores {
		if adapter.id == shardId {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.Read2(&mrpc.ReadUnshardedRequest[*types.Read2Request]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MyStubNonclusteredStub) Read3(ctx context.Context, req *types.Read3Request, opts ...mrpc.CallOption) (*types.Read3Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	for _, adapter := range s.myCoreCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.Read3(&mrpc.ReadRequest[*types.Read3Request]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MyStubNonclusteredStub) Update1(ctx context.Context, req *types.Update1Request, opts ...mrpc.CallOption) (*types.Update1Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	shardKey := req.ShardKey()
	for _, adapter := range s.myCoreCores {
		if shardKey >= adapter.lowerBound && shardKey <= adapter.upperBound {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.Update1(&mrpc.UpdateRequest[*types.Update1Request]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MyStubNonclusteredStub) Update2(ctx context.Context, req *types.Update2Request, shardId string, opts ...mrpc.CallOption) (*types.Update2Response, error) {
	settings := mrpc.ApplyCallOptions(opts...)
	now := time.Now().UnixNano()

	for _, adapter := range s.myCoreCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.Update2(&mrpc.UpdateUnshardedRequest[*types.Update2Request]{
				Now:     now,
				Payload: req,
			}, s.logger)
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			if settings.ResponseMeta != nil {
				*settings.ResponseMeta = mrpc.ResponseMeta{Now: now}
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MyStubNonclusteredStub) ListShards(applicationName string) ([]string, error) {
	switch applicationName {
	case "MyCore":
		shardIds := make([]string, len(s.myCoreCores))
		for i := range s.myCoreCores {
			shardIds[i] = s.myCoreCores[i].id
		}
		return shardIds, nil
	default:
		return nil, fmt.Errorf("application not found: %s", applicationName)
	}
}

func NewMyStubNonclusteredStub(shardsPerApp int, coresFactory *MyStubNonclusteredApplicationCoresFactory, logger *slog.Logger) *MyStubNonclusteredStub {
	if shardsPerApp < 1 || int64(shardsPerApp) > int64(cluster.KeyspacePerApplication) || shardsPerApp&(shardsPerApp-1) != 0 {
		panic(fmt.Sprintf("shardsPerApp must be a power of 2 between 1 and 2^32, got %d", shardsPerApp))
	}

	if logger == nil {
		logger = slog.Default()
	}

	myCoreCores := make([]*myCoreCoreNonclusteredAdapter, shardsPerApp)

	shardSize := int64(cluster.KeyspacePerApplication) / int64(shardsPerApp)
	for i := 0; i < shardsPerApp; i++ {
		lowerBound := cluster.ShardKey(int64(i) * shardSize)
		upperBound := cluster.ShardKey(int64(i+1)*shardSize - 1)

		sl, su := cluster.ShortenBounds(lowerBound.Bytes(), upperBound.Bytes())

		myCoreShardId := fmt.Sprintf("%s_%x_%x", "MyCore", sl, su)
		myCoreCores[i] = &myCoreCoreNonclusteredAdapter{core: coresFactory.MyCoreCoreFactoryFunc(myCoreShardId, lowerBound, upperBound), id: myCoreShardId, lowerBound: lowerBound, upperBound: upperBound}

	}
	return &MyStubNonclusteredStub{myCoreCores: myCoreCores, logger: logger}
}
