// Code generated by `monstera code generate`. DO NOT EDIT.

package codegen

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	monstera "github.com/evrblk/monstera"
	cluster "github.com/evrblk/monstera/cluster"
	types "github.com/evrblk/monstera/internal/integration_test/codegen/types"
	mrpc "github.com/evrblk/monstera/rpc"
	"sync"
	"time"
)

type MyStubMonsteraStub struct {
	monsteraClient *monstera.Client
}

var _ MyStubClientApi = &MyStubMonsteraStub{}

func (s *MyStubMonsteraStub) Read1(ctx context.Context, methodReq *types.Read1Request) (*types.Read1Response, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 1,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MyCore", methodReq.ShardKey(), false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Read1Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Read2(ctx context.Context, methodReq *types.Read2Request, shardId string) (*types.Read2Response, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 2,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.ReadShard(ctx, "MyCore", shardId, false, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Read2Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Read3(ctx context.Context, methodReq *types.Read3Request) (*types.Read3Response, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 3,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Read(ctx, "MyCore", methodReq.ShardKey(), true, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Read3Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Update1(ctx context.Context, methodReq *types.Update1Request) (*types.Update1Response, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 1,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.Update(ctx, "MyCore", methodReq.ShardKey(), rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Update1Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) Update2(ctx context.Context, methodReq *types.Update2Request, shardId string) (*types.Update2Response, error) {
	methodReqBytes, err := methodReq.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcReq := &mrpc.Request{
		Data:         methodReqBytes,
		MethodNumber: 2,
		Now:          time.Now().UnixNano(),
	}
	rpcReqBytes, err := rpcReq.MarshalVT()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	rpcRespBytes, err := s.monsteraClient.UpdateShard(ctx, "MyCore", shardId, rpcReqBytes)
	if err != nil {
		return nil, err
	}

	rpcResp := &mrpc.Response{}
	err = rpcResp.UnmarshalVT(rpcRespBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}
	methodResp := &types.Update2Response{}
	err = methodResp.UnmarshalBinary(rpcResp.Data)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return methodResp, nilifyIfEmpty(rpcResp.Error)
}

func (s *MyStubMonsteraStub) ListShards(applicationName string) ([]string, error) {
	shards, err := s.monsteraClient.ListShards(applicationName)
	if err != nil {
		return nil, err
	}
	shardIds := make([]string, len(shards))
	for i := range shards {
		shardIds[i] = shards[i].Id
	}
	return shardIds, nil
}

func NewMyStubMonsteraStub(monsteraClient *monstera.Client) *MyStubMonsteraStub {
	return &MyStubMonsteraStub{monsteraClient: monsteraClient}
}

func nilifyIfEmpty(err *mrpc.Error) error {
	if err == nil || err.Code == mrpc.ErrorCode_INVALID || err.Code == mrpc.ErrorCode_OK {
		return nil
	} else {
		return err
	}
}

type myCoreCoreNonclusteredAdapter struct {
	core       MyCoreCoreApi
	mu         sync.RWMutex
	id         string
	lowerBound []byte
	upperBound []byte
}

type MyStubNonclusteredApplicationCoresFactory struct {
	MyCoreCoreFactoryFunc func(shardId string, lowerBound []byte, upperBound []byte) MyCoreCoreApi
}
type MyStubNonclusteredStub struct {
	myCoreCores []*myCoreCoreNonclusteredAdapter
}

var _ MyStubClientApi = &MyStubNonclusteredStub{}

func (s *MyStubNonclusteredStub) Read1(ctx context.Context, req *types.Read1Request) (*types.Read1Response, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.myCoreCores {
		if bytes.Compare(shardKey, adapter.upperBound) <= 0 && bytes.Compare(shardKey, adapter.lowerBound) >= 0 {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.Read1(&mrpc.ReadRequest[*types.Read1Request]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MyStubNonclusteredStub) Read2(ctx context.Context, req *types.Read2Request, shardId string) (*types.Read2Response, error) {
	for _, adapter := range s.myCoreCores {
		if adapter.id == shardId {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.Read2(&mrpc.ReadUnshardedRequest[*types.Read2Request]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MyStubNonclusteredStub) Read3(ctx context.Context, req *types.Read3Request) (*types.Read3Response, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.myCoreCores {
		if bytes.Compare(shardKey, adapter.upperBound) <= 0 && bytes.Compare(shardKey, adapter.lowerBound) >= 0 {
			adapter.mu.RLock()
			defer adapter.mu.RUnlock()

			resp, err := adapter.core.Read3(&mrpc.ReadRequest[*types.Read3Request]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MyStubNonclusteredStub) Update1(ctx context.Context, req *types.Update1Request) (*types.Update1Response, error) {
	shardKey := req.ShardKey()
	for _, adapter := range s.myCoreCores {
		if bytes.Compare(shardKey, adapter.upperBound) <= 0 && bytes.Compare(shardKey, adapter.lowerBound) >= 0 {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.Update1(&mrpc.UpdateRequest[*types.Update1Request]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardKey: %s", shardKey)
}

func (s *MyStubNonclusteredStub) Update2(ctx context.Context, req *types.Update2Request, shardId string) (*types.Update2Response, error) {
	for _, adapter := range s.myCoreCores {
		if adapter.id == shardId {
			adapter.mu.Lock()
			defer adapter.mu.Unlock()

			resp, err := adapter.core.Update2(&mrpc.UpdateUnshardedRequest[*types.Update2Request]{
				Now:     time.Now().UnixNano(),
				Payload: req,
			})
			if err != nil {
				return nil, err
			}
			err = nilifyIfEmpty(resp.ApplicationError)
			if err != nil {
				return nil, err
			}
			return resp.Payload, nil
		}
	}

	return nil, fmt.Errorf("no shard found for shardId: %s", shardId)
}

func (s *MyStubNonclusteredStub) ListShards(applicationName string) ([]string, error) {
	switch applicationName {
	case "MyCore":
		shardIds := make([]string, len(s.myCoreCores))
		for i := range s.myCoreCores {
			shardIds[i] = s.myCoreCores[i].id
		}
		return shardIds, nil
	default:
		return nil, fmt.Errorf("application not found: %s", applicationName)
	}
}

func NewMyStubNonclusteredStub(shardsPerApp int, coresFactory *MyStubNonclusteredApplicationCoresFactory) *MyStubNonclusteredStub {
	myCoreCores := make([]*myCoreCoreNonclusteredAdapter, shardsPerApp)

	shardSize := cluster.KeyspacePerApplication / shardsPerApp
	for i := 0; i < shardsPerApp; i++ {
		lower := uint32(i * shardSize)
		upper := uint32((i+1)*shardSize - 1)
		lowerBound := make([]byte, 4)
		upperBound := make([]byte, 4)
		binary.BigEndian.PutUint32(lowerBound, lower)
		binary.BigEndian.PutUint32(upperBound, upper)

		sl, su := cluster.ShortenBounds(lowerBound, upperBound)

		myCoreShardId := fmt.Sprintf("%s_%x_%x", "MyCore", sl, su)
		myCoreCores[i] = &myCoreCoreNonclusteredAdapter{core: coresFactory.MyCoreCoreFactoryFunc(myCoreShardId, lowerBound, upperBound), id: myCoreShardId, lowerBound: lowerBound, upperBound: upperBound}

	}
	return &MyStubNonclusteredStub{myCoreCores: myCoreCores}
}
