// Code generated by `monstera code generate`. DO NOT EDIT.

package codegen

import (
	monstera "github.com/evrblk/monstera"
	mrpc "github.com/evrblk/monstera/rpc"
	"io"
)

type MyCoreValidatingCore struct {
	core MyCoreCoreApi
}

var _ MyCoreCoreApi = &MyCoreValidatingCore{}

func NewMyCoreValidatingCore(core MyCoreCoreApi) *MyCoreValidatingCore {
	return &MyCoreValidatingCore{core: core}
}

func (v *MyCoreValidatingCore) Snapshot() monstera.ApplicationCoreSnapshot {
	return v.core.Snapshot()
}

func (v *MyCoreValidatingCore) Restore(readers ...io.ReadCloser) error {
	return v.core.Restore(readers...)
}

func (v *MyCoreValidatingCore) Close() {
	v.core.Close()
}

func (v *MyCoreValidatingCore) Read1(req *Read1Request) (*Read1Response, error) {
	if err := req.Payload.Validate(); err != nil {
		return &Read1Response{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Read1(req)
}

func (v *MyCoreValidatingCore) Read2(req *Read2Request) (*Read2Response, error) {
	if err := req.Payload.Validate(); err != nil {
		return &Read2Response{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Read2(req)
}

func (v *MyCoreValidatingCore) Read3(req *Read3Request) (*Read3Response, error) {
	if err := req.Payload.Validate(); err != nil {
		return &Read3Response{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Read3(req)
}

func (v *MyCoreValidatingCore) Update1(req *Update1Request) (*Update1Response, error) {
	if err := req.Payload.Validate(); err != nil {
		return &Update1Response{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Update1(req)
}

func (v *MyCoreValidatingCore) Update2(req *Update2Request) (*Update2Response, error) {
	if err := req.Payload.Validate(); err != nil {
		return &Update2Response{ApplicationError: mrpc.NewError(mrpc.InvalidRequest, err.Error())}, nil
	}
	return v.core.Update2(req)
}
