// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: internal/replication/replicationpb/replication.proto

package replicationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandRouting tells the split seeder how to route an update entry to the
// children of a splitting shard.
type CommandRouting int32

const (
	// Proposed by a leader that was not in splitting mode — either the shard is
	// not splitting (the common case), or the leader had not applied the
	// splitting config yet. In the latter case the entry is unroutable and the
	// seeder restarts the affected children from a fresh base.
	CommandRouting_COMMAND_ROUTING_UNSTAMPED CommandRouting = 0
	// A sharded update: shard_key routes the entry to the child that owns it.
	CommandRouting_COMMAND_ROUTING_SHARDED CommandRouting = 1
	// A shard-wide (unsharded) update: seeded to every child in full.
	CommandRouting_COMMAND_ROUTING_SHARD_WIDE CommandRouting = 2
)

// Enum value maps for CommandRouting.
var (
	CommandRouting_name = map[int32]string{
		0: "COMMAND_ROUTING_UNSTAMPED",
		1: "COMMAND_ROUTING_SHARDED",
		2: "COMMAND_ROUTING_SHARD_WIDE",
	}
	CommandRouting_value = map[string]int32{
		"COMMAND_ROUTING_UNSTAMPED":  0,
		"COMMAND_ROUTING_SHARDED":    1,
		"COMMAND_ROUTING_SHARD_WIDE": 2,
	}
)

func (x CommandRouting) Enum() *CommandRouting {
	p := new(CommandRouting)
	*p = x
	return p
}

func (x CommandRouting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandRouting) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_replication_replicationpb_replication_proto_enumTypes[0].Descriptor()
}

func (CommandRouting) Type() protoreflect.EnumType {
	return &file_internal_replication_replicationpb_replication_proto_enumTypes[0]
}

func (x CommandRouting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandRouting.Descriptor instead.
func (CommandRouting) EnumDescriptor() ([]byte, []int) {
	return file_internal_replication_replicationpb_replication_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_INVALID CommandType = 0
	// An application update; payload is the application request.
	CommandType_COMMAND_TYPE_UPDATE CommandType = 1
	// No-op: applied without touching the core. Used as the index-contiguity
	// filler in seeded child logs (the sibling's routed entries).
	CommandType_COMMAND_TYPE_NOOP CommandType = 2
	// Shard-split cutoff: freezes the (parent) shard at this entry's index and
	// activates its children. Payload is a Cutoff message.
	CommandType_COMMAND_TYPE_CUTOFF CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_INVALID",
		1: "COMMAND_TYPE_UPDATE",
		2: "COMMAND_TYPE_NOOP",
		3: "COMMAND_TYPE_CUTOFF",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_INVALID": 0,
		"COMMAND_TYPE_UPDATE":  1,
		"COMMAND_TYPE_NOOP":    2,
		"COMMAND_TYPE_CUTOFF":  3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_replication_replicationpb_replication_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_internal_replication_replicationpb_replication_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_internal_replication_replicationpb_replication_proto_rawDescGZIP(), []int{1}
}

type MonsteraCommand struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Payload []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Type    CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=evrblk.monstera.replication.CommandType" json:"type,omitempty"`
	// Routing of this update for split seeding, stamped by the leader at
	// propose time only while this shard is SPLITTING. UNSTAMPED (the zero
	// value) at all other times: it costs nothing outside a split.
	Routing CommandRouting `protobuf:"varint,3,opt,name=routing,proto3,enum=evrblk.monstera.replication.CommandRouting" json:"routing,omitempty"`
	// The update's shard key; meaningful only when routing == SHARDED.
	ShardKey      uint32 `protobuf:"fixed32,4,opt,name=shard_key,json=shardKey,proto3" json:"shard_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsteraCommand) Reset() {
	*x = MonsteraCommand{}
	mi := &file_internal_replication_replicationpb_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsteraCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsteraCommand) ProtoMessage() {}

func (x *MonsteraCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_replication_replicationpb_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsteraCommand.ProtoReflect.Descriptor instead.
func (*MonsteraCommand) Descriptor() ([]byte, []int) {
	return file_internal_replication_replicationpb_replication_proto_rawDescGZIP(), []int{0}
}

func (x *MonsteraCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MonsteraCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_INVALID
}

func (x *MonsteraCommand) GetRouting() CommandRouting {
	if x != nil {
		return x.Routing
	}
	return CommandRouting_COMMAND_ROUTING_UNSTAMPED
}

func (x *MonsteraCommand) GetShardKey() uint32 {
	if x != nil {
		return x.ShardKey
	}
	return 0
}

// Cutoff is the payload of COMMAND_TYPE_CUTOFF.
type Cutoff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentShardId string                 `protobuf:"bytes,1,opt,name=parent_shard_id,json=parentShardId,proto3" json:"parent_shard_id,omitempty"`
	ChildShardIds []string               `protobuf:"bytes,2,rep,name=child_shard_ids,json=childShardIds,proto3" json:"child_shard_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cutoff) Reset() {
	*x = Cutoff{}
	mi := &file_internal_replication_replicationpb_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cutoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cutoff) ProtoMessage() {}

func (x *Cutoff) ProtoReflect() protoreflect.Message {
	mi := &file_internal_replication_replicationpb_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cutoff.ProtoReflect.Descriptor instead.
func (*Cutoff) Descriptor() ([]byte, []int) {
	return file_internal_replication_replicationpb_replication_proto_rawDescGZIP(), []int{1}
}

func (x *Cutoff) GetParentShardId() string {
	if x != nil {
		return x.ParentShardId
	}
	return ""
}

func (x *Cutoff) GetChildShardIds() []string {
	if x != nil {
		return x.ChildShardIds
	}
	return nil
}

var File_internal_replication_replicationpb_replication_proto protoreflect.FileDescriptor

const file_internal_replication_replicationpb_replication_proto_rawDesc = "" +
	"\n" +
	"4internal/replication/replicationpb/replication.proto\x12\x1bevrblk.monstera.replication\"\xcd\x01\n" +
	"\x0fMonsteraCommand\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12<\n" +
	"\x04type\x18\x02 \x01(\x0e2(.evrblk.monstera.replication.CommandTypeR\x04type\x12E\n" +
	"\arouting\x18\x03 \x01(\x0e2+.evrblk.monstera.replication.CommandRoutingR\arouting\x12\x1b\n" +
	"\tshard_key\x18\x04 \x01(\aR\bshardKey\"X\n" +
	"\x06Cutoff\x12&\n" +
	"\x0fparent_shard_id\x18\x01 \x01(\tR\rparentShardId\x12&\n" +
	"\x0fchild_shard_ids\x18\x02 \x03(\tR\rchildShardIds*l\n" +
	"\x0eCommandRouting\x12\x1d\n" +
	"\x19COMMAND_ROUTING_UNSTAMPED\x10\x00\x12\x1b\n" +
	"\x17COMMAND_ROUTING_SHARDED\x10\x01\x12\x1e\n" +
	"\x1aCOMMAND_ROUTING_SHARD_WIDE\x10\x02*p\n" +
	"\vCommandType\x12\x18\n" +
	"\x14COMMAND_TYPE_INVALID\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_UPDATE\x10\x01\x12\x15\n" +
	"\x11COMMAND_TYPE_NOOP\x10\x02\x12\x17\n" +
	"\x13COMMAND_TYPE_CUTOFF\x10\x03B?Z=github.com/evrblk/monstera/internal/replication/replicationpbb\x06proto3"

var (
	file_internal_replication_replicationpb_replication_proto_rawDescOnce sync.Once
	file_internal_replication_replicationpb_replication_proto_rawDescData []byte
)

func file_internal_replication_replicationpb_replication_proto_rawDescGZIP() []byte {
	file_internal_replication_replicationpb_replication_proto_rawDescOnce.Do(func() {
		file_internal_replication_replicationpb_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_replication_replicationpb_replication_proto_rawDesc), len(file_internal_replication_replicationpb_replication_proto_rawDesc)))
	})
	return file_internal_replication_replicationpb_replication_proto_rawDescData
}

var file_internal_replication_replicationpb_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_replication_replicationpb_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_replication_replicationpb_replication_proto_goTypes = []any{
	(CommandRouting)(0),     // 0: evrblk.monstera.replication.CommandRouting
	(CommandType)(0),        // 1: evrblk.monstera.replication.CommandType
	(*MonsteraCommand)(nil), // 2: evrblk.monstera.replication.MonsteraCommand
	(*Cutoff)(nil),          // 3: evrblk.monstera.replication.Cutoff
}
var file_internal_replication_replicationpb_replication_proto_depIdxs = []int32{
	1, // 0: evrblk.monstera.replication.MonsteraCommand.type:type_name -> evrblk.monstera.replication.CommandType
	0, // 1: evrblk.monstera.replication.MonsteraCommand.routing:type_name -> evrblk.monstera.replication.CommandRouting
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_replication_replicationpb_replication_proto_init() }
func file_internal_replication_replicationpb_replication_proto_init() {
	if File_internal_replication_replicationpb_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_replication_replicationpb_replication_proto_rawDesc), len(file_internal_replication_replicationpb_replication_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_replication_replicationpb_replication_proto_goTypes,
		DependencyIndexes: file_internal_replication_replicationpb_replication_proto_depIdxs,
		EnumInfos:         file_internal_replication_replicationpb_replication_proto_enumTypes,
		MessageInfos:      file_internal_replication_replicationpb_replication_proto_msgTypes,
	}.Build()
	File_internal_replication_replicationpb_replication_proto = out.File
	file_internal_replication_replicationpb_replication_proto_goTypes = nil
	file_internal_replication_replicationpb_replication_proto_depIdxs = nil
}
