// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: internal/replication/replicationpb/replication.proto

package replicationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_INVALID CommandType = 0
	CommandType_COMMAND_TYPE_UPDATE  CommandType = 1
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_INVALID",
		1: "COMMAND_TYPE_UPDATE",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_INVALID": 0,
		"COMMAND_TYPE_UPDATE":  1,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_replication_replicationpb_replication_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_internal_replication_replicationpb_replication_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_internal_replication_replicationpb_replication_proto_rawDescGZIP(), []int{0}
}

type MonsteraCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Type          CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=evrblk.monstera.replication.CommandType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsteraCommand) Reset() {
	*x = MonsteraCommand{}
	mi := &file_internal_replication_replicationpb_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsteraCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsteraCommand) ProtoMessage() {}

func (x *MonsteraCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_replication_replicationpb_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsteraCommand.ProtoReflect.Descriptor instead.
func (*MonsteraCommand) Descriptor() ([]byte, []int) {
	return file_internal_replication_replicationpb_replication_proto_rawDescGZIP(), []int{0}
}

func (x *MonsteraCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MonsteraCommand) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_INVALID
}

var File_internal_replication_replicationpb_replication_proto protoreflect.FileDescriptor

const file_internal_replication_replicationpb_replication_proto_rawDesc = "" +
	"\n" +
	"4internal/replication/replicationpb/replication.proto\x12\x1bevrblk.monstera.replication\"i\n" +
	"\x0fMonsteraCommand\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12<\n" +
	"\x04type\x18\x02 \x01(\x0e2(.evrblk.monstera.replication.CommandTypeR\x04type*@\n" +
	"\vCommandType\x12\x18\n" +
	"\x14COMMAND_TYPE_INVALID\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_UPDATE\x10\x01B?Z=github.com/evrblk/monstera/internal/replication/replicationpbb\x06proto3"

var (
	file_internal_replication_replicationpb_replication_proto_rawDescOnce sync.Once
	file_internal_replication_replicationpb_replication_proto_rawDescData []byte
)

func file_internal_replication_replicationpb_replication_proto_rawDescGZIP() []byte {
	file_internal_replication_replicationpb_replication_proto_rawDescOnce.Do(func() {
		file_internal_replication_replicationpb_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_replication_replicationpb_replication_proto_rawDesc), len(file_internal_replication_replicationpb_replication_proto_rawDesc)))
	})
	return file_internal_replication_replicationpb_replication_proto_rawDescData
}

var file_internal_replication_replicationpb_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_replication_replicationpb_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_replication_replicationpb_replication_proto_goTypes = []any{
	(CommandType)(0),        // 0: evrblk.monstera.replication.CommandType
	(*MonsteraCommand)(nil), // 1: evrblk.monstera.replication.MonsteraCommand
}
var file_internal_replication_replicationpb_replication_proto_depIdxs = []int32{
	0, // 0: evrblk.monstera.replication.MonsteraCommand.type:type_name -> evrblk.monstera.replication.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_replication_replicationpb_replication_proto_init() }
func file_internal_replication_replicationpb_replication_proto_init() {
	if File_internal_replication_replicationpb_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_replication_replicationpb_replication_proto_rawDesc), len(file_internal_replication_replicationpb_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_replication_replicationpb_replication_proto_goTypes,
		DependencyIndexes: file_internal_replication_replicationpb_replication_proto_depIdxs,
		EnumInfos:         file_internal_replication_replicationpb_replication_proto_enumTypes,
		MessageInfos:      file_internal_replication_replicationpb_replication_proto_msgTypes,
	}.Build()
	File_internal_replication_replicationpb_replication_proto = out.File
	file_internal_replication_replicationpb_replication_proto_goTypes = nil
	file_internal_replication_replicationpb_replication_proto_depIdxs = nil
}
